# Generated by Django 2.1.1 on 2018-11-06 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pie_staff_app', '0002_pieuser_isstaff'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pieuser',
            old_name='isStaff',
            new_name='is_staff',
        ),
    ]
