# Generated by Django 2.1.1 on 2018-11-06 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pie_staff_app', '0004_pieuser_has_module_perms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pieuser',
            name='has_module_perms',
        ),
    ]
