# Generated by Django 2.1.1 on 2018-11-06 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pie_staff_app', '0005_remove_pieuser_has_module_perms'),
    ]

    operations = [
        migrations.AddField(
            model_name='pieuser',
            name='username',
            field=models.CharField(default='jeromewei@pioneers.berkeley.edu', max_length=255),
            preserve_default=False,
        ),
    ]
