# Generated by Django 2.1.1 on 2018-11-06 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pie_staff_app', '0007_auto_20181106_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
