# Generated by Django 2.1.1 on 2018-11-10 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pie_staff_app', '0011_auto_20181107_0000'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='create_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
