# Generated by Django 2.1.1 on 2018-11-10 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pie_staff_app', '0012_issue_create_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
