# Generated by Django 2.1.1 on 2018-11-10 21:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pie_staff_app', '0013_auto_20181110_2134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='create_date',
        ),
        migrations.AddField(
            model_name='issue',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
